### ISSUE TITLE
对 `#12` 作出的解释

### ISSUE THREAD

**Issue by yuangusmam** [Happy2018new/DreamLand-YingLunTown#18]
确定处理办法如下。
***
1. 主要涉事者 `kono远古哒(gameUUID=00000000-0000-4000-8000-0000789f4ba6,qqid=3337501468)` 需要在国庆节结束前给出解释。
   > **最迟在本月结束前给出解释，否则后果自负。**
2. 予以主要涉事者 `蓝氏蓝某人(1940195721)` 进行批评教育并群内禁言处理 `3 Days`
   > 过失：即便有理但言语上多次存在过失，扰乱群内正常交流秩序。**介于行为的正义性，免除惩处，但仅限本次，下不为例。**
3. 予以其他涉事者 `纪辞.(3157424295)` 进行批评教育并群内禁言处理 `7 Days`
   > 过失：无需解释，**因为违背 季度更迭·会议商议 之精神**，予以较重处罚
***
此处理方法立即执行。
由于现行规定还尚未完成扁平化工作，因此上述决策未参考有关规定。
***
其他材料
![image](https://user-images.githubusercontent.com/109064184/193500227-4395d0eb-d46e-4b8f-92d8-600b3d70b330.png)
![image](https://user-images.githubusercontent.com/109064184/193500190-c9322ef1-40e0-4a1c-ae3e-d4eb57a26699.png)

_Originally posted by @Happy2018new in https://github.com/Happy2018new/DreamLand-YingLunTown/issues/12#issuecomment-1264906112_

**Comment by yuangusmam** [comment]
解释是

**Comment by yuangusmam** [comment]
> 
在大概9.24~9.25当天我在主城对一个新玩家进行了刮甲导致的

**Comment by Happy2018new** [comment]
祝贺你，你终于学会在 `Github` 上反馈事项了。

**Comment by Happy2018new** [comment]
请求已被接受，已撤销封禁状态。
