### ISSUE TITLE
地皮坐标申请

### ISSUE THREAD

**Issue by yuangusmam** [Happy2018new/DreamLand-YingLunTown#19]
申请进行字幕家坐标的维护以及服务器内威胁事件
1图为字幕君家坐标的维护（至于为什么维护?因为我是他邻居）
2图为服务器内玩家@神 意图以我新住宅的安全进行绑架（给他们无偿充当提供大量劳动力）
并且该地方坐标位置是由我一人选定所以以后我申请：未经我允许其他玩家禁止随意带领其他玩家进入该坐标附近
![Screenshot_20221107_184141_9143f33b2387a160d15fb9194169309e](https://user-images.githubusercontent.com/117568354/200359249-594acec6-28c3-4c8a-b937-5f11924275cc.jpg)
![Screenshot_2022_1107_223540](https://user-images.githubusercontent.com/117568354/200359316-875bb965-9111-4cdc-a6ab-f48b9ba6127b.jpg)

**Comment by yuangusmam** [comment]
并且他们已经在我探索坐标附近保存我申请将他们进入该坐标附近的权限封禁@傲雪寻梅 @神

**Comment by yuangusmam** [comment]
坐标会在处理结果通过后私发与管理

**Comment by Happy2018new** [comment]
此请求已被接受，请提供相应的坐标数据，格式如下。
***
格式一
```
字幕君家   [球心坐标] [球的半径]
远古家   [球心坐标] [球的半径]
```
***
格式二
```
字幕君家   [起点坐标] [终点坐标]
远古家   [起点坐标] [终点坐标]
```

**Comment by Happy2018new** [comment]
需要说明的是，如果提供的区域太大，那么我们可能会拒绝设置地皮。
允许的最大长度或宽度是 `200 方块` ，对于超过这个量级的地皮，我们不予创建。

**Comment by yuangusmam** [comment]
>选用格式二远古家坐标：起始坐标332440  200  －19733 
终点坐标332604  0  －19556
由于字幕君新家已被损坏所以说不确定他是否要对已经损坏的家进行保护暂等他上线
地皮保护白名单所需添加用户lD：我布是远古 字幕君___

**Comment by Happy2018new** [comment]
将会定义的地皮区域如下。
```
Name - Default 0
Owner - kono远古哒(gameUUID=00000000-0000-4000-8000-0000789f4ba6,qqid=3337501468)
The administrators of this area - [@Owner]
Area - From (332440,200,-19733) To (332604,0,-19556)
Size - 165 * 201 * 178 / 29,370 Block^2 / 5,903,370 Block^3
Allow List - [@Owner, @a[m=1], '我布是远古', '字幕君___']
Method of verification - Old Version(Depends on the name of the player)
```

**Comment by Happy2018new** [comment]
The command will be
```
execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,x=332440,y=0,z=-19733,dx=164,dy=200,z=177] ~ ~ ~ title @s actionbar 此区域已被设置地皮，您不被允许进入。
execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,x=332440,y=0,z=-19733,dx=164,dy=200,z=177] ~ ~ ~ gamerule sendcommandfeedback true
execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,x=332440,y=0,z=-19733,dx=164,dy=200,z=177] ~ ~ ~  tp 71 113 -96 facing 71 113 -97
```

**Comment by Happy2018new** [comment]
down.

**Comment by Happy2018new** [comment]
由于 #20 所述之请求，因此地皮相关信息将会变更。
(Allow List / Append - '花柠柠柠柠z')

**Comment by Happy2018new** [comment]
地皮信息变更为：
```
Name - Default 0
Owner - kono远古哒(gameUUID=00000000-0000-4000-8000-0000789f4ba6,qqid=3337501468)
The administrators of this area - [@Owner]
Area - From (332440,200,-19733) To (332604,0,-19556)
Size - 165 * 201 * 178 / 29,370 Block^2 / 5,903,370 Block^3
Allow List - [@Owner, @a[m=1], '我布是远古', '字幕君___', '花柠柠柠柠z']
Method of verification - Old Version(Depends on the name of the player)
```

**Comment by Happy2018new** [comment]
The commands will be
`execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,name=!花柠柠柠柠z,m=!1,x=332440,y=0,z=-19733,dx=164,dy=200,dz=177] ~ ~ ~ title @s actionbar 此区域已被设置地皮，您不被允许进入。`
`execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,name=!花柠柠柠柠z,m=!1,x=332440,y=0,z=-19733,dx=164,dy=200,dz=177,m=!1] ~ ~ ~ gamerule sendcommandfeedback true`
`execute @a[name=!kono远古哒,name=!我布是远古,name=!字幕君___,name=!花柠柠柠柠z,m=!1,x=332440,y=0,z=-19733,dx=164,dy=200,dz=177,m=!1] ~ ~ ~  tp 71 113 -96 facing 71 113 -97`

**Comment by Happy2018new** [comment]
down.
